version: '4'
services:
  app:
    image: space-ship-project-image
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb  
 