version: '4'
services:
  app:
    image: spaceship-image:tag
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb  
 